### ISSUE TITLE
Service no more available ?

### ISSUE THREAD

**Issue by avilleret** [aodendaal/unitybuildbadgeservice#2]
I would like to add a badge for my Unity Cloud Build status but, it seems that your wonderful solution doesn't work anymore.

I tried to follow the setup steps, but my Unity Cloud Build webhook setup wizard ask me for an authorization key. 
Moreover the URL seems to be a dead link.

Did I miss something ?

**Comment by aodendaal** [comment]
The project is dead because it was costing me money to host. I hope you can find another solution
